NOTE: Parameters to be given "target_hosts[---, desktop, tomcat]", "tfm_action[apply, destroy, ansible]", "ansible_action[---,apply, destroy]"
==============================================
pipeline {
    agent {
        label 'docker'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/summu97/ASSESMENT.git'
            }
        }
        stage('tfm-init') {
            when {
                expression {
                    return tfm_action == 'apply' || tfm_action == 'destroy'
                }
            }
            steps {
                sh '''
                cd /var/lib/jenkins/workspace/desktop/terraform-desktop
                terraform init
                '''
            }
        }
        stage('tfm-plan') {
            when {
                expression {
                    return tfm_action == 'apply'
                }
            }
            steps {
                sh '''
                cd /var/lib/jenkins/workspace/desktop/terraform-desktop
                terraform plan
                '''
            }
        }
        stage('tfm-action') {
            when {
                expression {
                    return tfm_action == 'apply' || tfm_action == 'destroy'
                }
            }
            steps {
                sh '''
                cd /var/lib/jenkins/workspace/desktop/terraform-desktop
                terraform $tfm_action --auto-approve
                '''
            }
        }
        stage('ansible.cfg') {
            when {
                expression {
                    return tfm_action == 'ansible'
                }
            }
            steps {
                sh 'cat ./ansible/ansible.cfg | sudo tee /etc/ansible/ansible.cfg'
                }
        }
        stage('Playbook execution'){
             when {
                expression {
                    return tfm_action == 'ansible'
                }
            }
            steps {
                sh 'ansible-playbook -e "target_hosts=$target_hosts" -e "operation=$ansible_action" ansible/master.yaml'
            }
        }
    }
}
